import os
import json
import math
import re
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

_client = Groq(api_key=os.environ["GROQ_API_KEY"])

SYSTEM_PROMPT = (
    "You are an AI authorship detection system. "
    "Evaluate the text provided by the user and assess the probability that it was generated by an AI. "
    "Consider phrasing predictability, transitional idioms, logical uniformity, and semantic tone. "
    "Respond with ONLY a JSON object in this exact format, no prose, no markdown: "
    '{\"ai_probability\": <float between 0.0 and 1.0>}'
)


def analyze_with_groq(text: str) -> float:
    """
    Returns a float in [0.0, 1.0] representing the probability the text is AI-generated.
    Returns 0.5 (neutral) if the response cannot be parsed.
    """
    try:
        response = _client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            temperature=0.0,
            max_tokens=64,
        )
        raw = response.choices[0].message.content.strip()
        score = json.loads(raw)["ai_probability"]
        return float(max(0.0, min(1.0, score)))
    except (json.JSONDecodeError, KeyError, TypeError) as e:
        print(f"[signals] Groq parse error: {e} | raw response: {raw!r}")
        return 0.5
    except Exception as e:
        print(f"[signals] Groq API error: {e}")
        return 0.5


def analyze_stylometrics(text: str) -> float:
    """
    Returns a float in [0.0, 1.0] where 0.0 = high human variance, 1.0 = uniform/AI.
    Uses only the Python standard library.
    """
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    words = re.findall(r"[a-z']+", text.lower())

    # Short text: not enough signal, return neutral
    if len(sentences) < 2 or len(words) == 0:
        return 0.5

    # Burstiness: std dev of sentence lengths (in words)
    sent_lengths = [len(re.findall(r"[a-z']+", s.lower())) for s in sentences]
    mean_len = sum(sent_lengths) / len(sent_lengths)
    variance = sum((l - mean_len) ** 2 for l in sent_lengths) / len(sent_lengths)
    burstiness = math.sqrt(variance)

    # Lexical diversity: unique words / total words (Type-Token Ratio)
    lexical_diversity = len(set(words)) / len(words)

    # Normalize burstiness: cap at 20 (very high variance) and invert so high variance → low score
    burstiness_score = 1.0 - min(burstiness / 20.0, 1.0)

    # Lexical diversity is already [0,1]; invert so high diversity → low score
    diversity_score = 1.0 - lexical_diversity

    # Combine: equal weight between the two sub-metrics
    signal_2 = (burstiness_score + diversity_score) / 2.0

    return round(max(0.0, min(1.0, signal_2)), 4)


def calculate_final_confidence(groq_score: float, stylo_score: float) -> float:
    """
    Combines Signal 1 (Groq) and Signal 2 (stylometrics) into a final confidence score.
    Applies a 0.5x penalty to the Groq score when stylometrics detect strong human
    variance (stylo_score < 0.30), preventing the LLM from unilaterally condemning
    a human writer.
    """
    if stylo_score < 0.30:
        effective_groq = groq_score * 0.5
    else:
        effective_groq = groq_score

    base_score = (effective_groq * 0.55) + (stylo_score * 0.45)
    return round(max(0.0, min(1.0, base_score)), 4)


if __name__ == "__main__":
    repetitive = (
        "The cat sat on the mat. The cat sat on the mat. The cat sat on the mat. "
        "The cat sat on the mat. The cat sat on the mat."
    )

    erratic = (
        "No. Absolutely not. I waited three hours in that car park — three hours — "
        "watching pigeons fight over a chip, and you're telling me the entire system "
        "just... crashed? Gone? Like it never existed? I had seventeen tabs open."
    )

    print(f"Repetitive text (expect high score): {analyze_stylometrics(repetitive)}")
    print(f"Erratic text    (expect low score):  {analyze_stylometrics(erratic)}")

    groq_sample = (
        "Furthermore, it is worth noting that the utilization of advanced language models "
        "has revolutionized the landscape of natural language processing. In conclusion, "
        "these transformative tools offer unprecedented opportunities for innovation."
    )
    print(f"\nGroq signal 1 test score: {analyze_with_groq(groq_sample)}")
